// Mocks generated by Mockito 5.4.4 from annotations
// in sophy/test/unit/music_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sophy/features/music/domain/entities/track.dart' as _i3;
import 'package:sophy/features/music/domain/repositories/music_repository.dart'
    as _i2;
import 'package:sophy/features/music/domain/usecases/get_recommendations.dart'
    as _i8;
import 'package:sophy/features/music/domain/usecases/get_tracks.dart' as _i4;
import 'package:sophy/features/music/domain/usecases/upload_track.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMusicRepository_0 extends _i1.SmartFake
    implements _i2.MusicRepository {
  _FakeMusicRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrack_1 extends _i1.SmartFake implements _i3.Track {
  _FakeTrack_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTracks].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTracks extends _i1.Mock implements _i4.GetTracks {
  MockGetTracks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MusicRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMusicRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MusicRepository);

  @override
  _i5.Future<List<_i3.Track>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<List<_i3.Track>>.value(<_i3.Track>[]),
      ) as _i5.Future<List<_i3.Track>>);
}

/// A class which mocks [UploadTrack].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadTrack extends _i1.Mock implements _i6.UploadTrack {
  MockUploadTrack() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MusicRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeMusicRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.MusicRepository);

  @override
  _i5.Future<_i3.Track> call({
    required String? name,
    required String? artist,
    required _i7.File? imageFile,
    required _i7.File? songFile,
    required String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #name: name,
            #artist: artist,
            #imageFile: imageFile,
            #songFile: songFile,
            #category: category,
          },
        ),
        returnValue: _i5.Future<_i3.Track>.value(_FakeTrack_1(
          this,
          Invocation.method(
            #call,
            [],
            {
              #name: name,
              #artist: artist,
              #imageFile: imageFile,
              #songFile: songFile,
              #category: category,
            },
          ),
        )),
      ) as _i5.Future<_i3.Track>);
}

/// A class which mocks [GetRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecommendations extends _i1.Mock
    implements _i8.GetRecommendations {
  MockGetRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Track> call({
    required List<_i3.Track>? allTracks,
    required List<_i3.Track>? favorites,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {
            #allTracks: allTracks,
            #favorites: favorites,
            #limit: limit,
          },
        ),
        returnValue: <_i3.Track>[],
      ) as List<_i3.Track>);
}
